### ISSUE TITLE
device 'iPhone14,7' could not be found in devicelist

### ISSUE THREAD

**Issue by notfleshka** [marijuanARM/futurerestore#161] opened 2024-04-09 10:18 UTC
Getting this error every time: User specified to use latest signed SEP
[Error] [TSSC] device 'iPhone14,7' could not be found in devicelist
futurerestore: failed with exception:
[exception]:
what=Could not find url of latest firmware version

**Comment by Cryptiiiic** [comment] 2024-05-24 07:03
Duplicate of #145

**Closed as completed by Cryptiiiic** 2024-05-24 07:03 UTC
Labels: bug, duplicate
